theme = "tokyonight"

[editor]
line-number = "relative"
mouse = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spacer", "version-control", "spacer", "separator", "file-name", "file-modification-indicator"]
center = []
right = ["spinner", "spacer", "diagnostics", "spacer", "selections", "separator", "file-encoding", "file-line-ending", "file-type", "separator", "spacer", "position-percentage", "position"]
separator = "│"
mode.normal = "N"
mode.insert = "I"
mode.select = "S"
